ITS-3252 PDV/IV remove NINO retrievals from Auth Session.
hmrc/find-your-national-insurance-number pull request #14
Opened 2024-01-15 14:59 UTC by rambabu-posa

2024-01-22 09:43 UTC, ajchilts requested changes

2024-01-22 09:43 UTC, ajchilts commented on test/controllers/IndividualsDetailsControllerSpec.scala
> +    "should return OK" in {
We do not need the word 'should'. If we read this back from the parent is states "getIndividualDetails must should return OK". Removing the 'should' makes this more readable.

2024-01-22 09:43 UTC, ajchilts commented on test/controllers/IndividualsDetailsControllerSpec.scala
>          status(result) mustBe 503
We probably want to refactor the asserts to use constants in the tests. Not 500, 503 etc.

2024-01-22 16:10 UTC, rishisachania approved these changes

2024-01-23 09:05 UTC, ajchilts approved these changes

2024-01-23 09:05 UTC, ajchilts commented on test/controllers/NPSFMNControllerSpec.scala
> +      val httpResponse = uk.gov.hmrc.http.HttpResponse(IM_A_TEAPOT, "happy new year")
😆

2024-01-23 10:30 UTC, merged